"use server";

import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";

export async function generateComplianceReport(organizationId: string) {
    const supabase = await createClient();
    const supabaseAdmin = createAdminClient();

    try {
        // 1. Verify permissions
        const { data: { user } } = await supabase.auth.getUser();
        if (!user) throw new Error("Unauthorized");

        const { data: member, error: memberError } = await supabase
            .from("organization_members")
            .select("role")
            .eq("organization_id", organizationId)
            .eq("user_id", user.id)
            .single();

        if (memberError || !member || (member.role !== "admin" && member.role !== "owner")) {
            throw new Error("You do not have permission to generate reports");
        }

        // 2. Fetch Data in Parallel
        const [
            orgResult,
            membersResult,
            apiKeysResult,
            webhooksResult,
            logsResult,
            rolesResult
        ] = await Promise.all([
            supabase.from("organizations").select("*").eq("id", organizationId).single(),
            supabase.from("organization_members").select("role, created_at, user_id").eq("organization_id", organizationId),
            supabase.from("api_keys").select("id, created_at, scope").eq("organization_id", organizationId),
            supabase.from("webhooks").select("id, url, events, is_active").eq("organization_id", organizationId),
            supabase.from("activity_logs").select("*").eq("organization_id", organizationId).order("created_at", { ascending: false }).limit(50),
            supabase.from("organization_roles").select("*").eq("organization_id", organizationId)
        ]);

        const org = orgResult.data;
        const members = membersResult.data || [];
        const apiKeys = apiKeysResult.data || [];
        const webhooks = webhooksResult.data || [];
        const logs = logsResult.data || [];
        const customRoles = rolesResult.data || [];

        // 3. Calculate Stats
        const admins = members.filter(m => m.role === 'admin' || m.role === 'owner');
        const owners = members.filter(m => m.role === 'owner');

        // 4. Generate Report Content
        const report = `
COMPLIANCE READINESS REPORT
================================================================
Organization: ${org?.name}
Report Date: ${new Date().toISOString()}
Generated By: ${user.email}
Report ID: ${crypto.randomUUID()}
================================================================

1. ORGANIZATION OVERVIEW
------------------------
Organization ID: ${organizationId}
Created At: ${new Date(org?.created_at).toLocaleString()}
Total Members: ${members.length}
Max Members Limit: ${org?.max_members || 10}
Max Teams Limit: ${org?.max_teams || 5}

2. ACCESS CONTROL & IDENTITY
----------------------------
Authentication: Supabase Auth (Secure JWT)
MFA Status: Optional (Enforcement configurable)
Session Management: Server-side tracking enabled

User Roles Distribution:
- Owners: ${owners.length}
- Admins: ${admins.length - owners.length}
- Members: ${members.length - admins.length}

Custom Roles Defined: ${customRoles.length}
${customRoles.map(r => `- ${r.name}: ${Object.keys(r.permissions || {}).filter(k => r.permissions[k]).join(', ')}`).join('\n')}

3. API & INTEGRATION SECURITY
-----------------------------
Active API Keys: ${apiKeys.length}
- Read Only: ${apiKeys.filter(k => k.scope === 'read_only').length}
- Read & Write: ${apiKeys.filter(k => k.scope === 'read_write').length}
Storage: Hashed (Argon2/Bcrypt) - Secrets not stored in plain text.

Active Webhooks: ${webhooks.length}
${webhooks.map(w => `- ${w.url} (${w.events.join(', ')}) [${w.is_active ? 'ACTIVE' : 'INACTIVE'}]`).join('\n')}

4. DATA PROTECTION & PRIVACY
----------------------------
Encryption at Rest: ENABLED (Supabase Storage / PostgreSQL)
Encryption in Transit: ENABLED (TLS 1.3)
Row Level Security (RLS): ENFORCED
- All queries are scoped to 'organization_id'
- Cross-tenant access strictly prohibited via database policies

5. RECENT AUDIT ACTIVITY (Last 50 Events)
-----------------------------------------
${logs.map(log => `[${new Date(log.created_at).toISOString()}] ${log.action.toUpperCase()} - User: ${log.user_id || 'System'}`).join('\n')}

================================================================
END OF REPORT
This report is for internal use and compliance readiness assessment.
================================================================
`;

        return { success: true, report };

    } catch (error: any) {
        console.error("Error generating report:", error);
        return { success: false, error: error.message };
    }
}
